name: laporan_akhir_shift
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  supabase_flutter: ^2.5.2
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  google_mobile_ads: ^4.0.0
  share_plus: ^11.0.0
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/images/img_1.jpeg
    - assets/images/img_2.jpeg
    - assets/images/img_3.jpeg
    - assets/images/img_4.jpeg
    - assets/images/img_5.jpeg
    - assets/images/img_6.jpeg
    - assets/images/img_7.jpeg
    - assets/images/img_8.jpeg
    - assets/images/img_9.jpeg
    - assets/images/img_10.jpeg

